### ISSUE TITLE
MBLD bug

### ISSUE THREAD

**Issue by TaxMas** [hato-ya/CubicTimer#130]
In multiblind, if you enter a solve like 3/7 solved and 2/7 solved with penalty, the solved with penalty are not aded to the other 3. So in this case it puts you a DNF.

If you do 3/5 solved and 2/5 solved with penalty in 10:00 mins, it gives you the two +2s, but in the final result it appears 3/5 10:04 instead of 5/5 10:04.

I would say that the problem is that the solved with penalties are not aded with the ones without penalties, but I'm not a programmer, so I don't know.

P.S. Well done with the aplication, every time it's getting better and more completed

**Comment by hato-ya** [comment]
Thank you for your confirmation.

It's current specification.

"Solved" is "Solved (including with a penalty)" as it is shown. So, if you solved 3/5 without a penalty and 2/5 with a penalty.
It is necessary to enter "5" to "Solved (including with a penalty)" and "2" to "Solved with a penalty".

**Comment by TaxMas** [comment]
Okay, sorry I had a missunderstan there, thanks for explaining it.
