### ISSUE TITLE
Individual color scheme

### ISSUE THREAD

**Issue by TaxMas** [hato-ya/CubicTimer#160]
A way to change any cubes scheme color individualy should be added. The color scheme of sq1 doesn't fit with my sq1, but if I change it the 3x3 color scheme also change. The same happends with the megaminx. 
A way to change any cubes scheme color without affecting the other categories should be in the application.

**Comment by hato-ya** [comment]
Thank you for your reporting and request.
I already received a similar request. I will try to fix it. But it will take some time.

**Comment by hato-ya** [comment]
I have implemented the following.
- Store individual color scheme
- Color scheme edit for Megaminx / Pyraminx / Clock

It will be included in the next release.

**Comment by hato-ya** [comment]
Cubic Timer 3.3.0 has been released.
It includes it.
