### ISSUE TITLE
Adding FTO

### ISSUE THREAD

**Issue by TaxMas** [hato-ya/CubicTimer#180]
This is only a proposal and due to that it is not official I would understand not doing it, but I will explain why at least it should be considered.

The Face Turning Octahedron is becoming more and more popular, and with the relase of the DianSheng Magnetic FTO even more.

I think that the adeition of this category will help to the future addition of the category, because that will show to the WCA that there is realy a big interest in it.

I know that there is the opption of "others" in the menu, but not having scrambles with the pictures doesn't show to delegates the interest for the puzzle.

Also, considering that the addition of FTO is probable, having it in advance would remove future work.

I know that this would be a lot of effort, but if you are able to do it, at least I want you to consider it, if not thanks for resding.

**Comment by hato-ya** [comment]
Thank you for your comment.

Currently, Cubic Timer relies on the WCA's library for scrambles and scramble images. So, it is hard to add a unique puzzle to the app.

However, I understand your request. There are some FTO fans in my country too.
We will add it to our list of considerations, but please temper your expectations.

**Comment by hato-ya** [comment]
FTO support is released as v3.4.0.
Currently, 30 random moves scramble is used.
