### ISSUE TITLE
OH and Multiblind

### ISSUE THREAD

**Issue by TaxMas** [hato-ya/CubicTimer#92]
Even if OH uses the 3x3 scrambles and Multiblind uses blind scrambles, I think that separated categories should be created (like 5x5 being separeted of 5x5bld).

Apart of this, multiblind results should be entered like in the WCA (z/y xx:xx.xx), taking in account the number of puzzles tried and solved. The multiblind category should have a way to enter the number of cubes wanted to try to generate that number of scrambles.

**Comment by hato-ya** [comment]
Thank you for your feedback.

Just now, we are implementing multi-blind.
It will have features including entering the number of attempted, generating the number of scrambles, handling the number of solved and time, and sorting by WCA order.

About OH, we would like to consider it. Technically, it is easy to add it.

**Comment by hato-ya** [comment]
MBLD support has been committed.
https://github.com/hato-ya/CubicTimer/commit/d50c1d55899119dbd92580abd338d8afcd930312

It will be included in the next release (Probably we'll submit it for Google review by the end of next week)

We will keep this issue for OH.

**Comment by hato-ya** [comment]
OH support has been committed.
As same as MBLD support, it will be included in the next release.

**Comment by hato-ya** [comment]
Cubic Timer 3.0.0 has been released.
It includes MBLD and OH support.
